### ISSUE TITLE
Error from the image zoom

### ISSUE THREAD

**Issue by jjhesk** [r0adkll/Slidr#12]
I have used the slidr with the photoview from chrisbanes. There are some out of bounds error i have found and they are listed here:

```
03-11 20:52:31.899  15048-15048/com.buildsystemexample.app.test_native E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.buildsystemexample.app.test_native, PID: 15048
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
            at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:848)
            at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1049)
            at com.r0adkll.slidr.widget.SliderPanel.onInterceptTouchEvent(SliderPanel.java:155)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2059)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2383)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1724)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2764)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2332)
            at android.view.View.dispatchPointerEvent(View.java:8655)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4094)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3635)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3694)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3660)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3773)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3668)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3830)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3640)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3694)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3660)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3668)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3640)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5940)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5872)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6030)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:211)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:197)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6001)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6062)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:792)
            at android.view.Choreographer.doCallbacks(Choreographer.java:596)
            at android.view.Choreographer.doFrame(Choreographer.java:555)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:778)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

It triggers when first there are two fingers touch the screen.

**Comment by jjhesk** [comment]
This is my native code 
```java

package com.hb.hkm.hypebeaststore;

import android.content.res.Configuration;
import android.graphics.Bitmap;
import android.graphics.RectF;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.TextView;

import com.hb.hkm.hypebeaststore.life.LifeCycleApp;
import com.lsjwzh.widget.materialloadingprogressbar.CircleProgressBar;
import com.r0adkll.slidr.Slidr;
import com.r0adkll.slidr.model.SlidrConfig;
import com.r0adkll.slidr.model.SlidrInterface;
import com.r0adkll.slidr.model.SlidrPosition;
import com.squareup.picasso.Callback;
import com.squareup.picasso.Picasso;
import com.squareup.picasso.Target;

import uk.co.senab.photoview.PhotoView;
import uk.co.senab.photoview.PhotoViewAttacher;


/**
 * Created by hesk on 3/3/15.
 */
public class zoomimage extends ActionBarActivity implements SlidrInterface {
    public static final String URLKEY = "image_url_full";
    public static final String TITLE = "title_bar_text";
    public static final String PHOTO_TAP_TOAST_STRING = "Photo Tap! X: %.2f %% Y:%.2f %% ID: %d";
    private static final String LOG_TAG = "image-test";

    private PhotoView mImage;
    private Button mButton1;
    private Button mButton2;
    private CheckBox mCheckBox;
    static int displayTypeCount = 0;
    private PhotoViewAttacher mAttacher;
    private TextView mCurrMatrixTv;
    private SlidrInterface slidrInf;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        final SlidrConfig config_slider = new SlidrConfig.Builder()
                .primaryColor(getResources().getColor(R.color.primary_pref))
                .secondaryColor(getResources().getColor(R.color.primary_pref_v2))
                .position(SlidrPosition.LEFT)
                .sensitivity(0.4f)
                .build();

        //   requestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.act_zoom_image);

        if (getIntent().getExtras() != null) {
            Bundle b = getIntent().getExtras();
            onSetLayout(b.getString(zoomimage.URLKEY));
            mCurrMatrixTv.setText(b.getString(zoomimage.TITLE));
            slidrInf = Slidr.attach(this, config_slider);
            slidrInf.unlock();
        }
    }

    private void onSetLayout(final String image_url) {
        mImage = (PhotoView) findViewById(R.id.vi);
        mCurrMatrixTv = (TextView) findViewById(R.id.textvi);
        final CircleProgressBar circle = (CircleProgressBar) findViewById(R.id.loading_bar);
        circle.setCircleBackgroundEnabled(false);
        circle.setShowArrow(false);
        circle.setColorSchemeResources(R.color.blue_400);
        final Picasso pica = ((LifeCycleApp) getApplication()).getInstancePicasso();
        Log.d(LOG_TAG, "load image with url : " + image_url);
        pica.load(image_url).into(mImage, new Callback() {
            @Override
            public void onSuccess() {
                mAttacher = new PhotoViewAttacher(mImage);
                mAttacher.setOnMatrixChangeListener(new MatrixChangeListener());
                mAttacher.setOnPhotoTapListener(new PhotoTapListener());
                circle.setVisibility(View.GONE);
                slidrInf.unlock();
            }

            @Override
            public void onError() {
                circle.setVisibility(View.GONE);
            }
        });


    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
    }

    @Override
    public void lock() {

    }

    @Override
    public void unlock() {

    }

    private class PhotoTapListener implements PhotoViewAttacher.OnPhotoTapListener {

        @Override
        public void onPhotoTap(View view, float x, float y) {
            float xPercentage = x * 100f;
            float yPercentage = y * 100f;
            //    Tool.trace(zoomimage.this,  String.format(PHOTO_TAP_TOAST_STRING, xPercentage, yPercentage, view == null ? 0 : view.getId()));
        }
    }

    private class MatrixChangeListener implements PhotoViewAttacher.OnMatrixChangedListener {

        @Override
        public void onMatrixChanged(RectF rect) {
            // mCurrMatrixTv.setText(rect.toString());
            //slidrInf.lock();
            if (mAttacher.getScale() == 0.0f)
                slidrInf.unlock();
            else
                slidrInf.lock();

        }
    }

}

```

**Comment by r0adkll** [comment]
These errors are occurring in the `ViewDragHelper` class that is supplied by the support library. See the _first_ two lines of the stacktrace: 

    at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:848)
    at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1049)

There is nothing I can really do besides wrapping the `mDragHelper.shouldInterceptTouchEvent(ev);` in a try-catch statement. I would recommend forking the library and wrapping that line in a try-catch and see if that works for you. If so you can make a pull request to the library and I'll merge it.

**Comment by AKiniyalocts** [comment]
Something similar happens when using PhotoView with a DrawerLayout. I don't believe there has been a fix for that yet either. You basically have to do the same thing @r0adkll suggests.

**Comment by jjhesk** [comment]
@AKiniyalocts @r0adkll So I am not sure where I suppose to start digging into the code. But I have the feeling this is going to be somewhere in the [panel code](https://github.com/r0adkll/Slidr/blob/master/library/src/main/java/com/r0adkll/slidr/widget/SliderPanel.java)

**Comment by r0adkll** [comment]
@jjhesk Right [here](https://github.com/r0adkll/Slidr/blob/master/library/src/main/java/com/r0adkll/slidr/widget/SliderPanel.java#L155) at line 155 specifically. Wrap that line in a try-catch statement.
