### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by wkq87** [r0adkll/Slidr#44]
i import this project,and run this example,here is the error log when i jump to the ViewerActivity.
`04-27 10:25:42.805 29616-29616/com.r0adkll.slidr.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.r0adkll.slidr.example, PID: 29616
                                                                           java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
                                                                               at com.r0adkll.slidr.model.SlidrPosition.$jacocoInit(SlidrPosition.java)
                                                                               at com.r0adkll.slidr.model.SlidrPosition.<clinit>(SlidrPosition.java)
                                                                               at com.r0adkll.slidr.example.ViewerActivity.onCreate(ViewerActivity.java:66)
                                                                               at android.app.Activity.performCreate(Activity.java:6272)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
                                                                               at android.app.ActivityThread.access$900(ActivityThread.java:157)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5530)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
                                                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline" on path: DexPathList[[zip file "/data/app/com.r0adkll.slidr.example-2/base.apk"],nativeLibraryDirectories=[/data/app/com.r0adkll.slidr.example-2/lib/arm, /vendor/lib, /system/lib]]
                                                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                               at com.r0adkll.slidr.model.SlidrPosition.$jacocoInit(SlidrPosition.java) 
                                                                               at com.r0adkll.slidr.model.SlidrPosition.<clinit>(SlidrPosition.java) 
                                                                               at com.r0adkll.slidr.example.ViewerActivity.onCreate(ViewerActivity.java:66) 
                                                                               at android.app.Activity.performCreate(Activity.java:6272) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494) 
                                                                               at android.app.ActivityThread.access$900(ActivityThread.java:157) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5530) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623) 
                                                                           	Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_b0d6a23.Offline
                                                                               at java.lang.Class.classForName(Native Method)
                                                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                               		... 16 more
                                                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Comment by ghanendrapiplani** [comment]
i am getting the same error on running the example

**Comment by r0adkll** [comment]
This should be resolved now.
