### ISSUE TITLE
Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by westlinkin** [r0adkll/Slidr#55]
when `<item name="android:windowIsTranslucent">true</item>` is set, app crashes on `setOrientation` method in `activity`.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
FATAL EXCEPTION: ControllerMessenger
Process: com.team_wye.gurunews, PID: 9834
java.lang.RuntimeException: Unable to start activity ComponentInfo{}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:466)
	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:420)
	at android.support.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:234)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:140)
	at android.support.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:123)
	at android.support.test.espresso.action.Tap.sendSingleTap(Tap.java:170)
	at android.support.test.espresso.action.Tap.access$100(Tap.java:31)
	at android.support.test.espresso.action.Tap$1.sendTap(Tap.java:46)
	at android.support.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:136)
	at android.support.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:355)
	at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:242)
	at android.support.test.espresso.ViewInteraction.access$100(ViewInteraction.java:62)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:149)
	at android.support.test.espresso.ViewInteraction$1.call(ViewInteraction.java:146)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:769)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.os.Parcel.readException(Parcel.java:1956)
	at android.os.Parcel.readException(Parcel.java:1894)
	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
	at android.app.Activity.setRequestedOrientation(Activity.java:5738)
	at com.team_wye.gurunews.activity.a.b(BaseActivity.kt:52)
	at com.team_wye.gurunews.activity.a.onCreate(BaseActivity.kt:30)
	at com.team_wye.gurunews.activity.NewsActivity.onCreate(NewsActivity.kt:49)
	at android.app.Activity.performCreate(Activity.java:6982)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:667)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	... 27 more

```

Related [SO post here](https://stackoverflow.com/a/46995624/1650683).

But if I want to publish this app to Google Play Store, I must update the target api level to the latest version, 27 for now. How to fix this?

**Comment by r0adkll** [comment]
This seems to be a bug in the latest `ActivityRecord.java` file in the sdk, which according to this https://issuetracker.google.com/issues/68454482 has been fixed but won't apply until future releases of the Android OS. 

There is nothing I can really do about this as `<item name="android:windowIsTranslucent">true</item>` is necessary for the entire library to work. Unless you need to compile against V27 for some feature in your app, you don't HAVE to compile with it to push to the store. Otherwise, there is nothing that can really be done here.
